# Generated by Django 3.2 on 2021-07-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_name',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
    ]
