# Generated by Django 3.2 on 2021-07-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_register_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
